console.log("===============================BANKS DETAILS======================================");
const sbiBank = {
    bankName : "SBIBANK",
    location : "pandharpur",
    accountNo : 37162593581,
    ifsc : 'SBIN0000446',
    interestRate : '9%',
}
console.log("1] SBI BANK DETAILS");
console.log(sbiBank);

console.log("====================================================");
const axisBank = {
    bankName : "AXIS BANK",
    location : "pune",
    accountNo : 967345261738453,
    ifsc : 'UTIB0000037',
    interestRate : '8.70%',
}
console.log("2] AXIS BANK DETAILS");
console.log(axisBank);

console.log("====================================================");
const hdfcBank = {
    bankName : "HDFC BANK",
    location : "Solapur",
    accountNo : 59135624378452,
    ifsc : 'HDFC0002819',
    interestRate : '8.40%',
}
console.log("3] HDFC BANK DETAILS");
console.log(hdfcBank);

console.log("====================================================");
const bankOfBaroda = {
    bankName : "BANK OF BARODA",
    location : "Pandharpur",
    accountNo : 59135624378452,
    ifsc : 'BARB0PANDHA',
    interestRate : '10.49%',
}
console.log("4]  BANK OF BARODA DETAILS");
console.log(bankOfBaroda);